service: tsubokawa23-star
frameworkVersion: "3"
provider:
  name: aws
  profile: nzu
  region: ap-northeast-1
  runtime: nodejs18.x
  environment:
    # ${sls:stage} は ${opt:stage, self:provider.stage, "dev"} のショートカット
    REGION: ${aws:region}
    S3_BUCKET: ${self:service}-${sls:stage}-bucket
    TZ: Asia/Tokyo
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:ListBucket'
            - 's3:PutObject'
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - 'Ref': 'S3Bucket'
                - '/*'
functions:
  create:
    handler: handlers/create.create
    memorySize: 4096
    events:
      - http:
          path: star
          method: post
          cors: true
    timeout: 30
  get:
    handler: handlers/list.list
    events:
      - http:
          path: star
          method: get
          cors: true
    timeout: 30
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        # AccessControl: PublicRead
        BucketName: ${self:provider.environment.S3_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
custom:
  # local S3 の設定
  s3:
    host: 127.0.0.1
    port: 4569
    directory: .buckets
plugins:
  - serverless-s3-local
  - serverless-offline